services:  
  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/etc/caddy/site
      - caddy_data:/data
      - caddy_config:/config
      - ./example-app:/var/www/example.app

volumes:
  caddy_data:
  caddy_config:
